name: placeholder-service
namespace: cloudvault
replicas: 2
port: 3000

image:
  repository: 806121398176.dkr.ecr.ap-south-1.amazonaws.com/cloudvault/placeholder
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

probes:
  livenessPath: /health
  readinessPath: /ready

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

env: []
