name: cart-service
port: 3003
image:
  repository: 806121398176.dkr.ecr.ap-south-1.amazonaws.com/cloudvault/cart-service
  tag: "latest"
  pullPolicy: IfNotPresent
env:
  - name: PORT
    value: "3003"
  - name: REDIS_URL
    value: "redis://redis:6379"
