name: notification-service
port: 3006
image:
  repository: 806121398176.dkr.ecr.ap-south-1.amazonaws.com/cloudvault/notification-service
  tag: "latest"
  pullPolicy: IfNotPresent
probes:
  livenessPath: /health
  readinessPath: /ready
