name: product-service
port: 3002
image:
  repository: 806121398176.dkr.ecr.ap-south-1.amazonaws.com/cloudvault/product-service
  tag: "latest"
  pullPolicy: IfNotPresent
env:
  - name: PORT
    value: "3002"
